### PR TITLE
TestCase001 Click Search Button Verification PASSED!!

### PR DESCRIPTION
**Pull request by MarkoDelije**
Hey Khrystyna and Oleh, please review "TestCase001_ClickSearchButton". Thank you!

### CODE REVIEW

**Review by KhrystynaN — APPROVED** [review]
I just noticed that you're merging to master branch!! Please change it to develop.

**Comment by mstoilkovic** [comment]
Look great!

**Review by mstoilkovic — APPROVED** [review]
Approved.

**Review by KhrystynaN — CHANGES_REQUESTED** [review]
Please merge it to develop branch, not to master. Thank you

**Review by OlehMashkin — APPROVED** [review]
Great!

**Review by OlehMashkin — APPROVED** [review]
That's great!

**Review by OlehMashkin — APPROVED** [review]
Approve

**Review by OlehMashkin — APPROVED** [review]
Approved

**Review by MarkoDelije — COMMENTED** [review]
I have changed the base from Master to develop branch. Thank you, please review my updated change

**Review by KhrystynaN — APPROVED** [review]
Good!

**Pull request merged**
